
# print(5 > 6)
# print(5 == 6 or 5 <= 6)
# print("====================================================")
# print(True and True)
# print(True and False)
# print (False and False)
# print("====================================================")
# print(True or True)
# print(True or False)
# print (False or False)
# print("====================================================")
# print(not True)
# print(not False)

a,b = 1,2
# print(a == a and b == b)
# print(a == a and b < a)
# print(a > b and b < a )
# print("====================================================")
# print(a == a or b == b)
# print(a == a or b < a)
# print(a > b or b < a )
# print("====================================================")
print(not b == b)
print(not b < a)
print(not b < a )